name: Tei To Turtle
#converts tei to ttl

on:
  push:
    paths:
      - "data/tei/tei_toBuild/**"
      - "!data/tei/tei_toBuild/README.md"
      
jobs:
  build:
    name: Build .ttl files
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Install          
        run: |          
          sudo bash install.sh
      - name: running tei transform
        run: |          
          . gh_tei2ttl.sh        
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
  deploy:
    name: Deploy .ttl files
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v3
      - name: Pushes ttl data to baernreither-app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "data/ttl/text"
          target-directory: "data/ttl/text"
          destination-github-username: "KfNGOe"
          destination-repository-name: "baernreither-app"
          user-email: baernreither-app@github.io
          target-branch: main      