name: Tei To TeiId
#converts tei to tei with xmlIds

on:
  push:
    paths:
      - "data/tei/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Install
        run: sudo bash install.sh
      - name: running tei transform
        run: . ghactions-tei2tei_id.sh
        env:
          changes: ${{ steps.files.outputs.all }}
      - name: Commit files
        run: |
          git config --global user.email "richard.hoermann@inode.at"
          git config --global user.name "rh1967"
          git add data          
          git commit -m "Update TEI files"
          git push
      - name: Pushes to dev-baernreither-app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "data/tei_xmlId"
          target-directory: "data/tei_xmlId"
          destination-github-username: "rh1967"
          destination-repository-name: "dev-baernreither-app"
          user-email: dev-baernreither-app@github.io
          target-branch: main