name: Tei To Turtle
#converts tei to ttl

on:
  push:
    paths:
      - "data/tei/**"
    paths-ignore:
      - "data/tei/README.md"
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Install
        run: sudo bash install.sh
      - name: running tei transform
        run: . ghactions-tei2ttl.sh
        env:
          changes: ${{ steps.files.outputs.all }}
      - name: Commit files
        run: |
          git config --global user.email "richard.hoermann@inode.at"
          git config --global user.name "rh1967"
          git add data          
          git commit -m "Update TEI files"
          git push
      - name: Pushes ttl data to baernreither-app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "data/ttl/text"
          target-directory: "data/ttl/text"
          destination-github-username: "KfNGOe"
          destination-repository-name: "baernreither-app"
          user-email: baernreither-app@github.io
          target-branch: main
      - name: Pushes xlsx data to baernreither-app
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "data/xlsx"
          target-directory: "data/xlsx"
          destination-github-username: "KfNGOe"
          destination-repository-name: "baernreither-app"
          user-email: baernreither-app@github.io
          target-branch: main